language: scala
scala:
  - "2.13.0-M4"
  - "2.12.7"
  - "2.11.12"
  - "2.10.7"
jdk:
  - oraclejdk8
sudo: false
matrix:
  include:
  - scala: 2.12.7
    jdk: oraclejdk10
  - scala: 2.13.0-M5
    script:
    - sbt
      "++ ${TRAVIS_SCALA_VERSION}"
      compile
