language: scala
dist: xenial
scala:
  - "2.13.1"
  - "2.12.10"
  - "2.11.12"
  - "2.10.7"
jdk:
  - openjdk8
sudo: false
matrix:
  include:
  - scala: 2.12.10
    jdk: openjdk11
  - os: windows
    language: bash
    env: JDK="adopt@1.8.212-04"
    before_script:
    - wget https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh
    - source .install-jdk-travis.sh
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/0ee2dae2eba72efb4a464a5ad255e348696ecda7/sbt && chmod +x ./sbt
    script:
    - ./sbt test
