language: scala
scala:
  - "2.13.0-M4"
  - "2.12.6"
  - "2.11.12"
  - "2.10.7"
jdk:
  - oraclejdk8
sudo: false
matrix:
  include:
  - scala: 2.12.6
    jdk: oraclejdk10
  - scala: 2.13.0-M5
    script:
    - sbt
      'set resolvers in ThisBuild += "staging" at "https://oss.sonatype.org/content/repositories/staging"'
      "++ ${TRAVIS_SCALA_VERSION}"
      compile
